backend:
  name: github
  repo: IYAOAA/1000HomeVibes
  branch: main
  base_url: https://decapcms-oauth.vercel.app
  auth_endpoint: auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "string" }
      - { label: "Link", name: "buy_link", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
